export * from './colors';
export * from './status';
export * from './errors';
export declare const UID: unique symbol;
export declare const PROXY: unique symbol;
export declare const REACTIVE: unique symbol;
export declare const AUTOGEN_COMMENTS = "\n\n/* ----- auto-generated code ----- */\n";
export declare const PRIMITIVES: string[];
export declare const SELF_CLOSE_TAGS: string[];
export declare const SERVING = "Serving at http://localhost:{0}\n\n";
